import React, { useState, useEffect, useContext } from "react";
import '@/styles/globals.css'
import Head from 'next/head'
import { useRouter } from 'next/router';

export default function App({ Component, pageProps }: any) {
  return (
    <>
      <Head>
        <title>Kennedy Creative</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Component {...pageProps} />
    </>
  )
}
